version: '3'
services:
  sonarqube:
    build: .
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://db:3306/sonarqube?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  db:
    image: postgres:14
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  # db:
  #   image: mysql:8.0
  #   container_name: sonarqube_db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=sonarqube
  #     - MYSQL_USER=sonar
  #     - MYSQL_PASSWORD=sonar
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonar_scanner
    depends_on:
      - sonarqube
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=admin
    volumes:
      - ./app:/usr/src
    command: >
      -Dsonar.projectKey=rcms-webapp
      -Dsonar.projectName=rcms-webapp
      -Dsonar.projectVersion=1
      -Dsonar.sources=/usr/src
      -Dsonar.language=php

  create-project:
    image: curlimages/curl:latest
    container_name: create_project
    depends_on:
      - sonarqube
    volumes:
      - ./create-project.sh:/usr/src/create-project.sh
    entrypoint: ["/bin/sh", "/usr/src/create-project.sh"]

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:

